FROM golang:1.15 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod tidy
COPY . .
RUN go build -o book-my-show .
FROM debian:bullseye-slim
WORKDIR /root/
COPY --from=builder /app/book-my-show .
EXPOSE 8080
CMD ["./book-my-show"]
